### ISSUE TITLE
Docker Images are too big

### ISSUE THREAD

**Issue by Shumakriss** [jboss-dockerfiles/drools#12]
First, let me just say thank you for creating these, they are awesome!

One thing that stood out to me was the time it took to download the images. I have a process where I need to transfer these offline and that can be more cumbersome (I realize I'm in a minority for that part).

That said, that indicates to me that there might be a better way. Has there been any effort into running this with Wildfly Swarm or some other lightweight solution?

**Comment by mbiarnes** [comment]
Hi @Shumakriss,

The docker images for drools/jpbm base inherit from jboss/wildfly:8.2.0.Final image which has a certain size.
In drools/jbpm base get deployed certain wars, that have their magnitude too.
Our images doesn't support Wildfly Swarm.
The best you can do is to squash or flatten the images somehow before transferring them.

Please look at:
http://jasonwilder.com/blog/2014/08/19/squashing-docker-images/
https://intercityup.com/blog/downsizing-docker-containers.html
http://tuhrig.de/flatten-a-docker-container-or-image/

Maybe this can help you somehow.

**Comment by Shumakriss** [comment]
Thank you @mbiarnes, I will take a look into some of those. I think I will still try to launch the jBPM WAR with Wildfly Swarm if I get some time down the road ;-)

**Comment by romartin** [comment]
Closing. Thanks for the feedback!
