### ISSUE TITLE
Where is your docker file?

### ISSUE THREAD

**Issue by sunshineo** [jboss-dockerfiles/drools#3]
I am trying to find it to see how to customize https://registry.hub.docker.com/u/jboss/drools-workbench/

**Comment by romartin** [comment]
Hey! Sorry for the late response.. I hope you already find it.  Anyway dockerfiles are in this repository:
- https://github.com/jboss-dockerfiles/drools/blob/master/drools-wb/base/Dockerfile
- https://github.com/jboss-dockerfiles/drools/blob/master/kie-server/base/Dockerfile

**Comment by sunshineo** [comment]
Thank you very much!
