### ISSUE TITLE
get Forbidden

### ISSUE THREAD

**Issue by hamidasgarian** [jboss-dockerfiles/drools#31]
i follow the instructions to install KIE Server showcase:
after execute command docker run -p 8180:8080 -d --name kie-server --link drools-wb:kie_wb jboss/kie-server-showcase:latest
the "drools-wb" is the name of my container that i run it with below command:
docker run -p 8080:8080 -p 8001:8001 -d --name drools-wb jboss/drools-workbench-showcase:latest

and container log is ok as below:

INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 10.0.0.Final (WildFly Core 2.0.10.Final) started in 52946ms - Started 847 of 1114 services (397 services are lazy, passive or on-demand)

in browser when i try http://my-ip:8180/kie-server/ get Forbidden. what is that damn thing?
how can i fix that?
actually i first run drools-workbench-showcase and then start kie-server-showcase .is that true?

**Comment by mbiarnes** [comment]
Hi,
The kie-server should be visible in drools-wb under the execution servers. 
Once you start a container with this the URL should be displayed and clicking on this you should access the server, without Forbidden.
