### ISSUE TITLE
Forbidden when running on AWS

### ISSUE THREAD

**Issue by jeffxor** [jboss-dockerfiles/drools#4]
I configured this to run through Elastic Beanstalk however when I log in I get forbidden. Any idea why?

**Comment by romartin** [comment]
Hey, honestly I don't have any idea about it sorry. 

But anyway keep in mind that these images do not met cloud environment requirements for services such as AWS or OpenShift (each one has different restrictions, etc), so the idea is just use the base images (eg: drools-wb, kie-server, jbpn-workbench... not showcases) for creating your custom one to deploy in your concrete environment.

This situation applies to other jboss community docker images as well, such as the jboss/wildfly one.  Other teams are building docker images specific for running in Openshift  but for the Amazon service there is no community side support.

From the other side, I would appreciate I somebody creates some of the drools/jbpm images for  Amazon and can share the information, as many people is asking about it.

**Comment by romartin** [comment]
I forgot to mention that these images use the "jboss" user, as you can see here -> https://github.com/jboss-dockerfiles/base/blob/master/Dockerfile#L18

As far as I know some cloud environments requires that containers have to be run as root, so probably the issues is related.

If you can check the logs and share them we can try to find out the issue, but I don't have an Amazon account any more so I can't test it :(
