### ISSUE TITLE
Support for docker-compose network when linking kie-server with workbench

### ISSUE THREAD

**Issue by juliaaano** [jboss-dockerfiles/drools#42]
It would be nice to have kie-server-showcase linked with the workbench using only docker networks and docker-compose. The --link docker feature is deprecated and if using via docker-compose, you don't get the expected variables to be injected in the container.

I would like to have one docker-compose with both kie-server and the workbench talking to each other in the same docker network.

See: https://docs.docker.com/compose/link-env-deprecated/

**Comment by juliaaano** [comment]
I volunteer to submit a PR, just let me know.

**Comment by sherl0cks** [comment]
@juliaaano I just hit this. I would encourage you to submit a PR here. it looks like all the magic needed is in the start script (https://github.com/jboss-dockerfiles/drools/blob/master/kie-server/showcase/etc/start_kie-server.sh)

**Comment by juliaaano** [comment]
@sherl0cks Thank you. I'll start working on this soon. Cheers.

**Comment by nmvprasad** [comment]
@juliaaano  did this issue is fixed?  then instead of using docker "--link " option how to link kie server with workbench?

**Comment by juliaaano** [comment]
@nmvprasad It's been a long time I haven't touched this, but I can tell you that you should be able to link the containers by simply running them in the same docker network. Using docker-compose it is more straightforward to achieve this.
