### ISSUE TITLE
Missing rest-all role

### ISSUE THREAD

**Issue by romartin** [jboss-dockerfiles/drools#6]
As described here 
http://mswiderski.blogspot.com.es/2015/09/unified-kie-execution-server-part-3.html
In the kie-server showcase image is missing the assigned role "rest-all" for the default user kie-server.

Check the discussion here https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!msg/drools-setup/4v6xhh0qFyU/glazhmisBAAJ

**Comment by mbiarnes** [comment]
@romartin https://github.com/jboss-dockerfiles/drools/pull/10
